### ISSUE TITLE
Real headless rendering 

### ISSUE THREAD

**Issue by Arthur151** [eth-ait/aitviewer#10]
Awesome project! The rendering works great on the desktop. 
But on the remote server, we may need a real headless rendering to avoid the error like:
(standalone) XOpenDistplay: cannot open display

**Comment by kaufManu** [comment]
The following should fix this problem (it essentially fakes the existence of a display device):

```
export DISPLAY=:0.0
Xvfb :0 -screen 0 640x480x24 &
```

This is usually sufficient for us. Did you have any other strategies for "real headless rendering" in mind? Would be curious to hear!

**Comment by kaufManu** [comment]
Closing this since this hasn't been active in a while. Feel free to re-open it again in the future if required.

**Comment by kunkun0w0** [comment]
Hi! Thanks for providing this solution for headless rendering.
But I meet an error message like this:
```
_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
_XSERVTransMakeAllCOTSServerListeners: server already running
(EE) 
Fatal server error:
(EE) Cannot establish any listening sockets - Make sure an X server isn't already running(EE) 
```
I try to change the display id like this:
```
Xvfb :1 -screen 0 640x480x24 &
export DISPLAY=:1.0
```
Then I meet this problem:
```
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
```
Would you like to help me with this? Do you have any other strategy for headless rendering?

**Comment by kaufManu** [comment]
This seems to be a configuration issue with your system's X server, so unfortunately I cannot offer too much help, as this highly depends on your setup (e.g. searching for your last error message suggests that Xvfb might want root access).

**Comment by MontaEllis** [comment]
> Hi! Thanks for providing this solution for headless rendering. But I meet an error message like this:
> 
> ```
> _XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
> _XSERVTransMakeAllCOTSServerListeners: server already running
> (EE) 
> Fatal server error:
> (EE) Cannot establish any listening sockets - Make sure an X server isn't already running(EE) 
> ```
> 
> I try to change the display id like this:
> 
> ```
> Xvfb :1 -screen 0 640x480x24 &
> export DISPLAY=:1.0
> ```
> 
> Then I meet this problem:
> 
> ```
> _XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
> ```
> 
> Would you like to help me with this? Do you have any other strategy for headless rendering?

same issue

**Comment by tanshiv2** [comment]
what is the server does not have Xvfb. Is there an alternative?

**Comment by sunshineinsandiego** [comment]
I am also having issues with headless rendering:

```
# export DISPLAY=:0.0
Xvfb :0 -screen 0 640x480x24 &
[1] 45
# The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Could not resolve keysym XF86CameraAccessEnable
> Warning:          Could not resolve keysym XF86CameraAccessDisable
> Warning:          Could not resolve keysym XF86CameraAccessToggle
> Warning:          Could not resolve keysym XF86NextElement
> Warning:          Could not resolve keysym XF86PreviousElement
> Warning:          Could not resolve keysym XF86AutopilotEngageToggle
> Warning:          Could not resolve keysym XF86MarkWaypoint
> Warning:          Could not resolve keysym XF86Sos
> Warning:          Could not resolve keysym XF86NavChart
> Warning:          Could not resolve keysym XF86FishingChart
> Warning:          Could not resolve keysym XF86SingleRangeRadar
> Warning:          Could not resolve keysym XF86DualRangeRadar
> Warning:          Could not resolve keysym XF86RadarOverlay
> Warning:          Could not resolve keysym XF86TraditionalSonar
> Warning:          Could not resolve keysym XF86ClearvuSonar
> Warning:          Could not resolve keysym XF86SidevuSonar
> Warning:          Could not resolve keysym XF86NavInfo
Errors from xkbcomp are not fatal to the X server
python
Python 3.10.18 (main, Jun  5 2025, 13:14:17) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from aitviewer.headless import HeadlessRenderer
>>> r = HeadlessRenderer()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/comotion/lib/python3.10/site-packages/aitviewer/headless.py", line 21, in __init__
    super().__init__(**kwargs)
  File "/opt/conda/envs/comotion/lib/python3.10/site-packages/aitviewer/viewer.py", line 127, in __init__
    self.window = base_window_cls(
  File "/opt/conda/envs/comotion/lib/python3.10/site-packages/moderngl_window/context/headless/window.py", line 27, in __init__
    self.init_mgl_context()
  File "/opt/conda/envs/comotion/lib/python3.10/site-packages/moderngl_window/context/headless/window.py", line 45, in init_mgl_context
    self._ctx = moderngl.create_standalone_context(
  File "/opt/conda/envs/comotion/lib/python3.10/site-packages/moderngl/__init__.py", line 2304, in create_standalone_context
    return create_context(standalone=True, **kwargs)
  File "/opt/conda/envs/comotion/lib/python3.10/site-packages/moderngl/__init__.py", line 2254, in create_context
    ctx.mglo, ctx.version_code = mgl.create_context(glversion=require, mode=mode, **settings)
  File "/opt/conda/envs/comotion/lib/python3.10/site-packages/glcontext/__init__.py", line 90, in create
    return x11.create_context(**kwargs)
Exception: (standalone) glXChooseFBConfig failed
>>> The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Could not resolve keysym XF86CameraAccessEnable
> Warning:          Could not resolve keysym XF86CameraAccessDisable
> Warning:          Could not resolve keysym XF86CameraAccessToggle
> Warning:          Could not resolve keysym XF86NextElement
> Warning:          Could not resolve keysym XF86PreviousElement
> Warning:          Could not resolve keysym XF86AutopilotEngageToggle
> Warning:          Could not resolve keysym XF86MarkWaypoint
> Warning:          Could not resolve keysym XF86Sos
> Warning:          Could not resolve keysym XF86NavChart
> Warning:          Could not resolve keysym XF86FishingChart
> Warning:          Could not resolve keysym XF86SingleRangeRadar
> Warning:          Could not resolve keysym XF86DualRangeRadar
> Warning:          Could not resolve keysym XF86RadarOverlay
> Warning:          Could not resolve keysym XF86TraditionalSonar
> Warning:          Could not resolve keysym XF86ClearvuSonar
> Warning:          Could not resolve keysym XF86SidevuSonar
> Warning:          Could not resolve keysym XF86NavInfo
Errors from xkbcomp are not fatal to the X server
```

Any suggestions?  For context, this is running in an Ubuntu 24.04 docker container on a headless VM. Thanks

**Comment by ayiyayi** [comment]
> what is the server does not have Xvfb. Is there an alternative?

same question, have you solved it? T_T
