### ISSUE TITLE
Questions about using SMPL-H

### ISSUE THREAD

**Issue by huzijun1996** [eth-ait/aitviewer#34]
I have downloaded the file (.pkl) from the website (https://mano.is.tue.mpg.de/download.php) as requested by Supported Body Models. and placed it in the correct location (... /data/smplx_models/smplh/SMPLH_FEMALE.pkl).However, when running load_AMASS.py in the examples folder, it still reports an error (I get the same error when running the official Quickstart provided):
Traceback (most recent call last):
  File "/home/xxx/Download/amass-bml/aitviewer-main/examples/load_AMASS.py", line 30, in <module>
    seq_amass = SMPLSequence.from_amass(
  File "/home/xxx/anaconda3/envs/ait/lib/python3.9/site-packages/aitviewer/renderables/smpl.py", line 220, in from_amass
    smpl_layer = SMPLLayer(model_type="smplh", gender=body_data["gender"].item(), device=C.device)
  File "/home/xxx/anaconda3/envs/ait/lib/python3.9/site-packages/aitviewer/models/smpl.py", line 63, in __init__
    self.bm = smplx.create(
  File "/home/xxx/anaconda3/envs/ait/lib/python3.9/site-packages/smplx/body_models.py", line 2402, in create
    return SMPLH(model_path, **kwargs)
  File "/home/xxx/anaconda3/envs/ait/lib/python3.9/site-packages/smplx/body_models.py", line 601, in __init__
    left_hand_components = data_struct.hands_componentsl[:num_pca_comps]
AttributeError: 'Struct' object has no attribute 'hands_componentsl'

**Comment by ramenguy99** [comment]
SMPL-H models require an additional step after download to merge the MANO and SMPL-H parameters and create the needed `SMPLH_FEMALE.pkl` file. This is described in the smplx package repository [here](https://github.com/vchoutas/smplx/blob/main/tools/README.md#merging-smpl-h-and-mano-parameters).

**Comment by huzijun1996** [comment]
Thank you for your help, this problem has been solved.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Dario ***@***.***&gt;; 
发送时间: 2023年6月20日(星期二) 凌晨0:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [eth-ait/aitviewer] Questions about using SMPL-H (Issue #34)





 
SMPL-H models require an additional step after download to merge the MANO and SMPL-H parameters and create the needed SMPLH_FEMALE.pkl file. This is described in the smplx package repository here.
