### ISSUE TITLE
AssertionError： load_DIP_TC.py

### ISSUE THREAD

**Issue by scholars-Lwp** [eth-ait/aitviewer#40]
when running examples\load_DIP_TC.py
reporting an error:
Traceback (most recent call last):
  File "c:/Users/xxx/Desktop/Project_report/aitviewer-main/aitviewer-main/examples/load_DIP_TC.py", line 41, in <module>
    _, joints = smpl_layer(
  File "D:\anaconda\envs\py3_8\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\anaconda\envs\py3_8\lib\site-packages\aitviewer\models\smpl.py", line 243, in forward
    return self.fk(*args, **kwargs)
  File "D:\anaconda\envs\py3_8\lib\site-packages\aitviewer\models\smpl.py", line 171, in fk
    assert poses_body.shape[1] == self.bm.NUM_BODY_JOINTS * 3
AssertionError

But I can't find a way to solve it. What should I do

**Comment by kaufManu** [comment]
Hi, I tested this with 1.12 and the `s1_acting1.pkl` sequence, but can't reproduce this error. What version of aitviewer are you using and which TotalCapture sequence are you trying to visualize?

**Comment by scholars-Lwp** [comment]
Thank you for your reply.The aitviewer version I use is 1.12.TotalCapture sequence is TotalCapture Real 60FPS/s1_acting1.pkl

**Comment by kaufManu** [comment]
Unfortunately I cannot reproduce this - could you please post an example that reproduces your error? Thanks.

**Comment by kaufManu** [comment]
Closing du the inactivity, feel free to re-open again should the problem persist.
