### ISSUE TITLE
AttributeError : 'Struct' object has no attribute 'hands_componentsl'

### ISSUE THREAD

**Issue by yhiroya2000** [eth-ait/aitviewer#63]
Hi, 
When I tried to run the quick start code, this error happened.

```
code$ python3 test.py
WARNING: You are using a SMPL+H model, with only 10 shape coefficients.
Traceback (most recent call last):
  File "/home/code/test.py", line 6, in <module>
    v.scene.add(SMPLSequence.t_pose())
  File "/home/y/.local/lib/python3.10/site-packages/aitviewer/renderables/smpl.py", line 301, in t_pose
    smpl_layer = SMPLLayer(model_type="smplh", gender="neutral")
  File "/home/y/.local/lib/python3.10/site-packages/aitviewer/models/smpl.py", line 48, in __init__
    self.bm = smplx.create(
  File "/home/y/.local/lib/python3.10/site-packages/smplx/body_models.py", line 2402, in create
    return SMPLH(model_path, **kwargs)
  File "/home/y/.local/lib/python3.10/site-packages/smplx/body_models.py", line 601, in __init__
    left_hand_components = data_struct.hands_componentsl[:num_pca_comps]
AttributeError: 'Struct' object has no attribute 'hands_componentsl'

```

I've already added smplx models and changed yaml file.
What should I do to run this code?

**Comment by kaufManu** [comment]
This looks like a problem with your SMPL-H model files, see [here](https://github.com/vchoutas/smplx/issues/165). You have two options:
- pass the argument `ext='npz'` to the `SMPLLayer`. This would require that you change the `SMPLSequence.t_pose()` function as we did not account for that use case in that function. Or you can pass your own instance of `SMPLLayer` to that function. I'm no 100 % sure that this will work.
- Prepare your SMPL-H models as `.pkl` files, which is the recommended [way](https://github.com/vchoutas/smplx/blob/main/tools/README.md).

**Comment by yhiroya2000** [comment]
second one worked for me. Thank you so much!
