### ISSUE TITLE
Creating two Viewers after each other

### ISSUE THREAD

**Issue by DominikVincent** [eth-ait/aitviewer#66]
I want to display to viewers after each other:
1. create first viewer
2. close window
3. create second viewer
4. close window

However, this fails. Here is a minimal failing example:
```
v = Viewer()
v.run()

# Create a new Viewer instance
v = Viewer()
v.run()
```

The error is:
```
Traceback (most recent call last):
  File "/home/dominik/Documents/repos/UIPSip/scripts/ait_viewer_test.py", line 16, in <module>
    v = Viewer()
  File "/home/dominik/miniconda3/envs/UIP/lib/python3.8/site-packages/aitviewer/viewer.py", line 127, in __init__
    self.window = base_window_cls(
  File "/home/dominik/miniconda3/envs/UIP/lib/python3.8/site-packages/aitviewer/utils/pyqt5_window.py", line 92, in __init__
    self.init_mgl_context()
  File "/home/dominik/miniconda3/envs/UIP/lib/python3.8/site-packages/moderngl_window/context/base/window.py", line 173, in init_mgl_context
    self._ctx = moderngl.create_context(require=self.gl_version_code)
  File "/home/dominik/miniconda3/envs/UIP/lib/python3.8/site-packages/moderngl/__init__.py", line 1944, in create_context
    raise ValueError("Requested OpenGL version {0}, got version {1}".format(require, ctx.version_code))
ValueError: Requested OpenGL version 450, got version 0
```

The first viewer creating works fine. However, the second one fails. Could this be some issue with the moderngl context management?

I am on ubuntu 22.04 with python 3.8

**Comment by DominikVincent** [comment]
duplicate of
https://github.com/eth-ait/aitviewer/issues/12
